on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  ubuntu_tests:
    name: Test Sammy on Ubuntu
    runs-on: ubuntu-20.04
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2

      - name: 📥 Install Sammy Dependencies
        run: python3 setup.py install

      - name: ✨ Make a new project
        run: sammy start project

      - name: ✂️ Copy main.cpp -> 📋 app.cpp
        working_directory: project
        run: cp main.cpp app.cpp

      - name: 🛠️ Build Application (lpc40xx)
        working_directory: project
        run: |
        sammy build
        [-f ./build/lpc40xx/./lpc40xx.main.cpp.elf]

      - name: 🛠️ Build Application (lpc40xx) given source file
        working_directory: project
        run: |
        sammy build app.cpp
        [-f ./build/lpc40xx/./lpc40xx.app.cpp.elf]

      - name: 🛠️ Build Application (stm32f10x) given source file
        working_directory: project
        run: |
        sammy build app.cpp --platform stm32f10x
        [-f ./build/stm32f10x/./stm32f10x.app.cpp.elf]

      - name: 📥 Install libbasis
        working_directory: project
        run: |
        sammy install libbasis
        [-f ./packages/libbasis/libbasis]
        [-f ./library/libbasis]
        [ ! -f ./library/libbasis/libbasis]

      - name: 🗑️ Remove libbasis
        working_directory: project
        run: |
        sammy remove libbasis
        [ ! -f ./packages/libbasis/libbasis]
        [ ! -f ./library/libbasis]


